### ISSUE TITLE
Dependency injection sample failing in some cases

### ISSUE THREAD

**Issue by musictopia2** [davidwengier/SourceGeneratorPlayground#14]
I changed the code to this

using System;

namespace MyApp
{
    class Program
    {
        static void Main()
        {
            // Comment and uncomment these lines to see how the generation changes
            var foo = DI.ServiceLocator.GetService<IFoo>();

            var anotherFoo = DI.ServiceLocator.GetService<IFoo>();

            var bar = DI.ServiceLocator.GetService<IBar>();
            RegisterTest<ITest>();
            //// Uncomment to demonstrate build errors:
            // var baz = DI.ServiceLocator.GetService<IBaz>();

            Console.WriteLine("Hello World");
        }
        static void RegisterTest<T>()
        {
            var tt = DI.ServiceLocator.GetService<T>();
        }
    }
    interface ITest
    {

    }
    //// Comment and uncomment the attribute to see how the generation changes
    //[DI.Transient]
    interface IFoo
    {
    }

    class Foo : IFoo
    {
    }

    interface IBar
    {
    }

    class Bar : IBar
    {
    }

    interface IBaz
    {
    }
    class Test : ITest
    {

    }
}

When i run it, says Error(s) running generator:

warning CS8785: Generator 'DISourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'NullReferenceException' with message 'Object reference not set to an instance of an object.'

There are times when there is a public method and a person is using generics to decide what will register.  In this case, its now working.  Would be a shame if there was no way with source generators to make it work in that case since reflection is too slow.

**Comment by davidwengier** [comment]
The DI source generator is not intended to be a fully featured DI solution, just an example of a source generator, so it supporting generics is not really an issue.

I would suggest if you want a source-generated DI you would be better off looking at a project that is dedicated to that purpose, like StrongInject perhaps: https://github.com/YairHalberstadt/stronginject
