### ISSUE TITLE
NuGet Warning NU1603 & NuGet Warning NU1605

### ISSUE THREAD

**Issue by racoltacalin** [davidwengier/SourceGeneratorPlayground#8]
![image](https://user-images.githubusercontent.com/37398532/112811848-258d4f00-9085-11eb-8bcc-a4a32fce2a72.png)

**Comment by davidwengier** [comment]
I can't reproduce this, but I updated the compiler packages to newer ones, let me know if the issue goes away.

You didn't have any local changes to any files did you?

**Comment by racoltacalin** [comment]
I did not make any local changes.
Now it's working! Thanks for resolving this issue so quick.
